document:
  name: Linee d'Indirizzo del Modello Interoperabilità
  description: Linee d'Indirizzo del Modello Interoperabilità
  tags:
    - modello interoperabilita
    - linee guida
    - regole tecniche
