version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
            tox -e build
