openapi: 3.0.1
info:
 title: RESTCallbackServer
 version: "1.0"
 description: |-
   Questo file descrive semplicemente i metodi di un'API
   e non indica tutte le informazioni di metadatazione che
   normalmente vanno inserite.
 license:
   name: Apache 2.0 License
   url: http://www.apache.org/licenses/LICENSE-2.0.html
paths:
 /resources/{id_resource}/M:
   post:
     description: M
     operationId: PushMessage
     parameters:
     - name: X-ReplyTo
       in: header
       schema:
         type: string
     - name: id_resource
       in: path
       required: true
       schema:
         type: integer
         format: int32
     requestBody:
       content:
         application/json:
           schema:
             $ref: '#/components/schemas/MType'
     responses:
       202:
         description: Preso carico correttamente di M
         headers:
           X-Correlation-ID:
             required: true
             schema:
               type: string
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/ACKMessage'
       404:
         description: Identificativo non trovato
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/ErrorMessage'
       500:
         description: Errore interno avvenuto
         content:
           application/json:
             schema:
               $ref: '#/components/schemas/ErrorMessage'
     callbacks:
       completionCallback:
         '{$request.header#/X-ReplyTo}':
           post:
             requestBody:
               content:
                 application/json:
                   schema:
                     $ref: '#/components/schemas/MResponseType'
             responses:
               200:
                 description: Risposta correttamente ricevuta
                 content:
                   application/json:
                     schema:
                       $ref: '#/components/schemas/ACKMessage'
               404:
                 description: Identificativo non trovato
                 content:
                   application/json:
                     schema:
                       $ref: '#/components/schemas/ErrorMessage'
               500:
                 description: Errore interno avvenuto
                 content:
                   application/json:
                     schema:
                       $ref: '#/components/schemas/ErrorMessage'
components:
 schemas:
   MType:
     type: object
     properties:
       a:
         $ref: '#/components/schemas/AComplexType'
       b:
         type: string
   ACKMessage:
     type: object
     properties:
       outcome:
         type: string
   MResponseType:
     type: object
     properties:
       c:
         type: string
   AComplexType:
     type: object
     properties:
       a1s:
         type: array
         items:
           type: integer
           format: int32
       a2:
         type: string
   ErrorMessage:
     $ref: 'https://raw.githubusercontent.com/teamdigitale/openapi/0.0.4/docs/definitions.yaml#/schemas/Problem'